### ISSUE TITLE
UnboundLocalError: local variable 'feat_prop1' referenced before assignment

### ISSUE THREAD

**Issue by JingYansen** [Kimsure/TCNet-for-VSR#2]
`def forward(self, x):
        flows_forward, flows_backward = self.get_flow(x)
        b, n, c, h, w = x.size()
        attention_feat = self.get_attention(x)
        # branch
        out_l = []
        out_l_attn = []
        feat_prop = x.new_zeros(b, self.num_feat, h, w)
        for i in range(n - 1, -1, -1):
            x_i = x[:, i, :, :, :]
            # print('test_backwardbranch')
            # print(x_i.shape)
            if i < n - 1:
                flow1 = flows_backward[:, i, :, :, :]
                flow2 = flows_forward[:, i, :, :, :]
                feat_prop1 = flow_warp(feat_prop, flow1.permute(0, 2, 3, 1))
                feat_prop2 = flow_warp(feat_prop, flow2.permute(0, 2, 3, 1))
            feat_prop = torch.cat([x_i, feat_prop1, feat_prop2], dim=1)`

In the first iteration, i=n-1, then feat_prop1 and feat_prop2 are undefined, so an error will happen: UnboundLocalError: local variable 'feat_prop1' referenced before assignment

**Comment by Kimsure** [comment]
we are sry for the mistakes, setting feat_prop1 and feat_prop2 as feat_prop might be right. We are double-checking these days
